<?xml version="1.0"?>
<package format="3">
  <name>world_handler</name>
  <version>0.0.0</version>
  <description>make gazebo world and spawn a 4wids vehicle</description>

  <!-- maintainer -->
  <maintainer email="mizuhoaoki1998@gmail.com">Mizuho Aoki</maintainer>

  <!-- license -->
  <license>MIT</license>

  <!-- dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <!-- Gazebo-related items are not yet ported in this package's launch. -->

  <!-- export gazebo asset paths -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
